# Config for human whole genome sequencing reports

subtitle: "SNP&SEQ Technology Platform"
intro_text: |
  This is a report containing quality control information about your project run at the SNP&SEQ Technology
  Platform. If you have any questions, please do not hesitate to contact us at
  <a href="mailto:seq@medsci.uu.se">seq@medsci.uu.se</a>

custom_logo: 'assets/UU_logo_tranp4f125px.png'
custom_logo_url: 'http://sequencing.se'
custom_logo_title: 'SNP&SEQ Technology Platform'

clarity:
    name_edit_regex: '^.*.\/(.*)_L00\d_[R|I]\d_001\.fastq\.gz$'

    report_header_info:
        Project:
            'Application':
            'Kit for library preparation':
            'DNA library insert size':
            'Sequencing instrument':
            'Read length bp':
            'Project decription':

    # TODO The sample level stats is something that we will need tp specify later.
    general_stats:
        Sample:
          'Fake Value':
#            'Read Length':
#                description: 'Sequencing read length'
#            'Insert size (bp)':
#                description: 'Target insert size'
#
    # TODO This does not actually work since the Clarity MultiQC module only works with
    #      MultiQC v1.0, and we are using v1.7
    clarity_module:
        Sample:
          'Fake Value':
#            'Read Length':
#                description: 'Sequencing read length'
#            'Insert size (bp)':
#                description: 'Target insert size'



table_columns_visible:
    FastQC:
        percent_duplicates: False
        percent_gc: False
        total_sequences: False

max_table_rows: 1000

# QC criteria for NGI Uppsala, based on values in INS-00123
# Compatible with MultiQC v1.6
table_cond_formatting_rules:
    mqc-generalstats-qualimap-percentage_aligned:
        pass:
            - gt: 97.1
        fail:
            - lt: 97.1

    mqc-generalstats-qualimap-avg_gc:
        pass:
            - gt: 40.5
            - lt: 42.1
        fail:
            - lt: 40.5
            - gt: 42.1

    mqc-generalstats-qualimap-median_insert_size:
        pass:
            - gt: 317
            - lt: 428
        fail:
            - lt: 317
            - gt: 428

    mqc-generalstats-qualimap-10_x_pc:
        pass:
            - gt: 91
        fail:
            - lt: 91

    mqc-generalstats-qualimap-30_x_pc:
        pass:
            - gt: 58
        fail:
            - lt: 58

    mqc-generalstats-snpeff-Number_of_variants_before_filter:
        pass:
            - gt: 4.8
            - lt: 5.3
        fail:
            - lt: 4.8
            - gt: 5.3

    mqc-generalstats-snpeff-Ts_Tv_ratio:
        pass:
            - gt: 1.98
            - lt: 2.01
        fail:
            - lt: 1.98
            - gt: 2.01
